// Loading and hint lines: mechanics help mixed with Runbook proverbs and Night Shift wisdom.

export const TIPS: string[] = [
  "Space pauses. Give orders while paused. The machines will wait; they have had practice.",
  "Every relay switch costs 1 TTL. At 0, no relay will switch you. Benches and exchanges can re-stamp your connection.",
  "The Seal comes from behind and never stops. Lingering keeps a route warm, and the Seal likes warm routes.",
  "Every 2 power in the Shield Array is one layer of ward mesh. A layer stops one bolt. Lances lose one point per layer.",
  "The handshake that lets you hop only goes out with someone at the helm. The Runbook never trusted a greeting to a machine alone.",
  "Never trust one road. Keep a second weapon powered, a second crew member near the ward mesh, a second way home.",
  "Slug throwers go straight through the ward mesh. Payloads also run out. Pell sells more, at fair prices.",
  "Jammers do no hull damage, but they strip the ward mesh and stun systems. Jam first, then talk.",
  "Optical lances hurt most against a bare mesh. Knock the layers down first.",
  "A fire eats air and systems. Open a hatch to the outside to let the thin air take it, then close it before the crew notice.",
  "Riggers do not breathe. Send one into a breached room and let the others keep their air.",
  "Riggers cannot use the Bench Infirmary. They mend themselves while they repair a system.",
  "A bellmaker tunes the system in the room they stand in. Put one somewhere that deserves an extra bar.",
  "Couriers are fastest at the helm or the engines. Wardens are best at the shields and in a fight.",
  "Human crews can surrender. Accepting is always an option, and out here people remember.",
  "A Listening Post at level 2 shows the enemy's rooms and crew. At level 3, its weapon charge.",
  "Blue choices need something aboard: a system, a weapon, a crew member, an augment. Look for them.",
  "Sealed relays are held by quarantine drones and hold nothing worth taking. Go around if you can.",
  "Hopping away from a fight forfeits the reward. It also forfeits the funeral.",
  "Be strict in what you send and generous in what you accept.",
  "A message that cannot die becomes a storm. Yours can die. Keep an eye on the TTL.",
  "Leave the lamp on for the next shift.",
  "You never take the Line down to fix it. Repair systems during the fight, not after.",
  "Machines are not killed. Their tasks end. Their salvage does not mind which.",
  "The Iron Regent wants to see you lose a road and keep coming. Spread your power.",
  "The Hollow Choir only breaks to many voices at once. Fire your weapons together.",
  "The Blackout Core fights in the order the Runbook gives: cut, breach, jam, strike. Then it spends its reserve.",
  "Every machine meets you as an unknown sender. Their keys expired thirty-one years ago. So did yours.",
  "Salvage is anything that outlived its owner. Spend it before it outlives you.",
  "Hello. — I hear you. — I hear you hear me. It is surprising how often that works.",
  "Kettle's on the shelf. Take a cup before you go on.",
  "The Drone Bay eats spares. Keep a few in the hold for the day a drone saves your hull.",
  "A Lamp-Dark Veil stops enemy weapons charging while it lasts. Save it for their big volley.",
  "Crawlers ride the carriers like you and swing slowly. Installations do not move at all. Drones on rotors are hard to hit.",
  "Evasion is the drive surging and swinging the car on its carrier. Keep the Thrusters powered and the helm manned.",
];
