// Headless combat balance runner. Plays every enemy against benchmark tenders with the autopilot and reports win
// rates, hull lost and fight length. Usage:
//   node --experimental-strip-types tools/balance/run.ts [--n 30] [--enemy id] [--out docs/balance-combat.md]
import { writeFileSync } from "node:fs";
import { Sim } from "../../src/combat/sim/sim.ts";
import { autoFight } from "../../src/combat/sim/autoplay.ts";
import { benchShip, benchInventory, type BenchLevel } from "../../src/combat/sim/bench.ts";
import { ENEMIES } from "../../src/data/enemies.ts";
import { ENEMY_IDS, type EnemyId, type StageIndex } from "../../src/game/ids.ts";

const args = process.argv.slice(2);
const opt = (k: string, d: string) => {
  const i = args.indexOf(`--${k}`);
  return i >= 0 ? args[i + 1] : d;
};
const N = Number(opt("n", "24"));
const only = opt("enemy", "");
const out = opt("out", "");

interface Row {
  enemy: EnemyId;
  stage: StageIndex;
  depth: number;
  level: BenchLevel;
  win: number;
  lose: number;
  other: number;
  hullLost: number;
  secs: number;
  crewLost: number;
  payloads: number;
}

function runOne(enemy: EnemyId, stage: StageIndex, depth: number, level: BenchLevel): Row {
  const row: Row = { enemy, stage, depth, level, win: 0, lose: 0, other: 0, hullLost: 0, secs: 0, crewLost: 0, payloads: 0 };
  for (let s = 0; s < N; s++) {
    const ship = benchShip(stage, level);
    const inv = benchInventory(stage);
    const def = ENEMIES[enemy];
    const sim = new Sim(ship, inv, { enemy, stage, seed: 9000 + s * 77, depth, boss: !!def.boss, surrenderable: def.kind === "human" });
    autoFight(sim, {}, 900);
    const r = sim.result();
    if (r.outcome === "victory" || r.outcome === "surrendered") row.win++;
    else if (r.outcome === "defeat") row.lose++;
    else row.other++;
    row.hullLost += ship.hull - (r.outcome === "defeat" ? 0 : r.ship.hull);
    row.secs += r.stats.seconds;
    row.crewLost += r.crewLost.length;
    row.payloads += inv.payloads - r.inventory.payloads;
  }
  return row;
}

const rows: Row[] = [];
const enemies = (only ? [only] : [...ENEMY_IDS]) as EnemyId[];
const t0 = Date.now();
for (const e of enemies) {
  const def = ENEMIES[e];
  const stages: StageIndex[] = e === "quarantine-drone" ? [1, 2, 3] : [def.stage];
  for (const st of stages) {
    const depths = def.boss ? [1] : [0.1, 0.9];
    for (const d of depths) {
      const levels: BenchLevel[] = def.boss ? ["starter", "typical", "strong"] : ["starter", "typical"];
      for (const lv of levels) {
        const r = runOne(e, st, d, lv);
        rows.push(r);
        const pct = Math.round((r.win / N) * 100);
        console.log(`${e.padEnd(18)} s${st} d${d} ${lv.padEnd(8)} win ${String(pct).padStart(3)}%  hull −${(r.hullLost / N).toFixed(1)}  ${(r.secs / N).toFixed(0)}s  crew −${(r.crewLost / N).toFixed(2)}  pay −${(r.payloads / N).toFixed(1)}`);
      }
    }
  }
}
console.log(`done in ${((Date.now() - t0) / 1000).toFixed(0)} s`);

if (out) {
  const lines = [
    "# Combat balance (headless)",
    "",
    `Generated by \`node --experimental-strip-types tools/balance/run.ts --n ${N} --out ${out}\` — ${N} fights per row,`,
    "autopilot player (`src/combat/sim/autoplay.ts`: volleys against shields, strips the shield room first, mans",
    "stations, repairs, fights boarders, accepts surrenders, never hops away). Benchmark tenders per stage are defined in",
    "`src/combat/sim/bench.ts` (starter = what you can have on entering the stage, typical = a sensible build midway,",
    "strong = a well-upgraded tender). Hull lost is averaged over all fights (a defeat counts the whole hull).",
    "",
    "| enemy | stage | depth | tender | win % | hull lost | seconds | crew lost | payloads used |",
    "|---|---|---|---|---|---|---|---|---|",
    ...rows.map((r) => `| ${r.enemy} | ${r.stage} | ${r.depth} | ${r.level} | ${Math.round((r.win / N) * 100)} | ${(r.hullLost / N).toFixed(1)} | ${(r.secs / N).toFixed(0)} | ${(r.crewLost / N).toFixed(2)} | ${(r.payloads / N).toFixed(1)} |`),
    "",
  ];
  writeFileSync(out, lines.join("\n"));
  console.log(`wrote ${out}`);
}
